name: Build & Push Docker Images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  generate-jobs:
    name: Generate  Jobs
    runs-on: ubuntu-latest
    outputs:
      strategy: ${{ steps.generate-jobs.outputs.strategy }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: php-actions/composer@v5
        with:
          only_args: --version
      - name: Add Composer Credentials
        run: composer config -g http-basic.repo.magento.com ${{ secrets.COMPOSER_AUTH_USERNAME }} ${{ secrets.COMPOSER_AUTH_PASSWORD }}
      - name: Add Magento Composer Repository
        run: composer config -g repo.packagist false && composer config -g repositories.repo.magento.com composer https://repo.magento.com
      - id: install-dependencies
        name: Install NPM Dependencies
        run: npm install
        working-directory: ./lib
      - id: generate-jobs
        name: Generate Jobs
        run: echo "::set-output name=strategy::{\"matrix\":{\"include\":$(npm run --silent versions)}}"
        working-directory: ./lib

  build:
    needs: generate-jobs
    strategy: ${{ fromJson(needs.generate-jobs.outputs.strategy) }}
    name: "${{ matrix.version }}-php-${{ matrix.php.version }}-${{ matrix.php.variant }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: build
        name: Build
        run: ${{ matrix.build }}
      - id: push
        name: Push
        run: docker push serializator/magento --all-tags
      - id: images
        name: Images
        run: docker image ls